import React from "react";

export default function Bai6() {
  return (
    <div>
      <p className="text-ellipsis overflow-y-scroll w-6/12 h-52">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ducimus sequi eaque quidem debitis nostrum architecto ex quam accusamus odio harum velit ut totam, ipsa possimus officia praesentium cumque nemo!
      Commodi quo cum nesciunt omnis odio possimus enim nostrum saepe perferendis culpa? Totam ea quas non veniam! Blanditiis eligendi dolore explicabo, laborum ad praesentium dolores, vitae quisquam inventore et nemo.
      At enim nulla, distinctio maiores laboriosam cumque provident quasi in, explicabo aut qui, eligendi repellat? Repellendus alias necessitatibus ad, molestias maiores tenetur similique incidunt eius error obcaecati dignissimos cum repudiandae.
      Commodi, distinctio minus fuga facere consequuntur dolore ducimus cumque, hic aut similique officiis eaque quidem laborum neque cupiditate quam cum architecto dolor adipisci ipsa ab perspiciatis fugit. Maxime, dolor voluptatem.
      Veritatis, perspiciatis voluptates velit vel magnam consectetur recusandae non minima quos ullam dolorem, perferendis rerum doloribus laboriosam asperiores magni consequuntur. Soluta nemo officiis assumenda optio eos maiores amet et voluptas.
      Cupiditate dolor, nesciunt nihil maxime a quis accusantium enim nobis doloribus pariatur voluptatum numquam molestias labore consectetur quos expedita blanditiis fuga? Asperiores vero quibusdam rem quia mollitia nulla, quaerat cupiditate!
      A error totam sequi, quas voluptatum provident sed, dolorem culpa quaerat soluta odio esse voluptate pariatur cumque excepturi, id quam suscipit deleniti illum quibusdam laborum maxime maiores ducimus reprehenderit. Incidunt!
      Ipsa cupiditate dolore similique nulla esse modi id veritatis cumque quia soluta, nesciunt est! Possimus eos, maiores temporibus sunt repudiandae similique facilis nulla? Eius cupiditate, quaerat molestias accusantium qui eaque!
      Aut culpa ratione quis, placeat non deleniti quo eos nobis officiis quae accusantium porro quisquam amet, libero quia. Possimus cum mollitia laboriosam debitis laudantium voluptates quas dolor amet officiis incidunt!
      Quos cupiditate, blanditiis sapiente vitae repellat, laborum explicabo dolores reprehenderit distinctio optio, omnis quod ipsa corrupti nulla neque hic. Mollitia, nobis vitae! Porro numquam eius quod placeat, aliquid officia enim!
      Voluptate illo nobis officiis. Obcaecati voluptatum, earum iure eius explicabo atque similique veritatis natus recusandae, nesciunt rerum est deserunt quibusdam dolorum saepe minus quidem porro. Vero incidunt consectetur reprehenderit aut!
      Excepturi, hic perferendis facilis possimus repellat eaque repudiandae voluptatibus dolor fugit rerum laborum at nam explicabo perspiciatis consequatur! Ipsam reiciendis ut corporis ratione veniam animi dicta modi sapiente at quasi!
      Illum, perspiciatis autem perferendis ullam eum libero. Quia molestiae accusamus ipsam aperiam velit! Recusandae hic labore deserunt sint fugit obcaecati. Qui iusto dolore sed rerum ex dicta! Illum, dolor. Reprehenderit!
      Consequuntur voluptatem commodi omnis corrupti amet mollitia perspiciatis non corporis! Obcaecati at dolore eligendi tempora dolores, praesentium delectus maxime. Excepturi ipsam vero delectus minima id tempora officia temporibus natus veritatis.
      Vitae ipsum temporibus cupiditate doloribus culpa quos, repudiandae quas optio adipisci itaque quaerat incidunt alias, accusamus repellat ex facilis explicabo dolore accusantium rerum enim blanditiis inventore commodi. Id, nobis asperiores?
      Numquam eos voluptate enim illo, explicabo hic quaerat dolore veritatis amet ab nemo dignissimos reiciendis quia doloribus, maxime eum sed quae! Amet odit, natus hic corrupti molestias porro assumenda perferendis?
      Hic facere dolorem et repellat tempora distinctio consequuntur aspernatur, ad officia necessitatibus autem, corporis nam nostrum sequi unde ab ipsam nemo numquam harum omnis? Modi ullam maxime atque magni et!
      Atque quia beatae nemo! Adipisci maxime expedita, harum nemo quaerat quis amet nihil inventore ullam reiciendis quia laboriosam eligendi ipsum nostrum! Aut itaque quas odio sequi cum, fugiat ex libero?
      Ab minima optio officia. Cum fuga perferendis voluptatibus, qui expedita hic dolor tenetur incidunt fugit repellendus aliquid dignissimos itaque debitis? Vitae neque, harum blanditiis et adipisci sapiente earum corrupti maiores!
      Delectus reiciendis harum quae fuga nesciunt placeat magnam veniam, itaque ullam cumque atque et nobis! Quidem facere voluptatum molestias dolorem, placeat animi debitis reiciendis, ipsam iusto asperiores rem odit nesciunt!
      Dolorum vel excepturi dolore fugit odit error ducimus dicta, explicabo voluptates consectetur! Harum quae nesciunt dolore corporis minima tenetur deserunt a laboriosam recusandae molestiae. Eum minima veniam quaerat eius et?
      Itaque quidem nesciunt a sapiente quam rerum magnam repellat, quaerat et nisi aliquid ipsa autem! Ducimus sequi, ipsa earum optio consequatur nisi, ipsum ab incidunt tenetur vel possimus iusto. Temporibus!
      Fuga eius ipsum nemo quos. Nesciunt laboriosam ullam natus ea ipsam animi illum, exercitationem neque incidunt laudantium id numquam at eligendi molestiae similique esse tenetur officiis! Numquam laborum distinctio unde!
      Iusto delectus eligendi harum repellat adipisci nostrum optio reiciendis facilis atque velit inventore quibusdam voluptatem quod eos magnam officia neque, iure beatae soluta cum? At aliquam et facere distinctio consequatur!
      At modi quasi in nemo ex. Consectetur rem aperiam voluptatum architecto illo laborum! Atque at quisquam consectetur perspiciatis quam iste officia deleniti similique iusto cumque nemo, recusandae est delectus ipsum?
      Architecto, voluptatum? Porro voluptates nemo sequi ut natus nobis voluptatem, alias, nihil sint impedit nisi delectus corporis repellat at corrupti quod blanditiis vel error consectetur iste? Iure incidunt laudantium odit?
      Quos ea esse minus aliquid amet saepe reiciendis cumque ipsam consectetur aperiam velit odio aspernatur, repellat alias repellendus enim? Possimus, praesentium! Officia excepturi, consectetur itaque recusandae a vel consequuntur debitis?
      Odio vero distinctio corporis! Quos voluptatum ut ab totam quibusdam, pariatur tempora perferendis eos vel non repellendus laborum in veniam ad, dolore similique aliquid, delectus aperiam nam voluptatibus? Praesentium, rem.
      Aliquid, eaque quas saepe quasi minima architecto. Itaque incidunt quas assumenda, suscipit eligendi quasi! Vero unde error expedita nesciunt, dolores, quae accusamus deleniti, numquam rerum fuga qui soluta aspernatur vitae!
      Soluta beatae molestiae ipsa debitis iste expedita non, sapiente fugit hic maiores natus ullam. Corporis voluptatum soluta culpa alias voluptatem tenetur provident amet repellat, fuga, rerum officiis animi, ab distinctio!
      Quibusdam ducimus et autem magni sit architecto rerum cum vero, repellat maxime soluta mollitia reiciendis ab delectus sapiente doloribus consectetur explicabo illo non qui nulla quasi atque! Ea, minima distinctio.
      Veniam dicta harum sapiente doloremque tenetur ducimus saepe culpa tempora consequatur. Maxime delectus culpa sit earum nihil rem tempora natus exercitationem. Fuga vel laboriosam cupiditate, asperiores rem ut soluta ratione!
      Consectetur mollitia quis a impedit, repellat, quibusdam sint officiis illo fugiat distinctio nam id sequi voluptas quasi ex, harum pariatur doloribus. Quod explicabo labore numquam illo ipsa sunt atque rem.
      Libero sint consequuntur natus placeat esse distinctio perferendis inventore harum necessitatibus! Architecto porro perferendis repellat minima repudiandae totam dolores cumque sit quaerat quisquam ad debitis, qui rem omnis laborum accusantium!
      Cupiditate explicabo itaque odit neque dicta repellat culpa mollitia velit dolore! Ipsam commodi doloribus, necessitatibus delectus ullam molestias laudantium odio sapiente aspernatur ut quidem voluptatibus inventore quas nam, alias dolor!
      Est voluptatibus iure culpa doloribus? Repellendus amet corrupti dolores obcaecati eveniet odio temporibus, beatae ea deleniti, suscipit ut dolorum fugit distinctio voluptates incidunt non sit nihil ullam provident, a minus!
      Asperiores veniam, quasi id accusamus expedita illo. Ab, officia nisi repudiandae beatae atque necessitatibus quam aspernatur perspiciatis odio incidunt consectetur obcaecati provident ea corrupti odit delectus, alias doloribus esse molestiae?
      Odit dolores perferendis sint quibusdam quisquam ad quo esse debitis hic, tempore facilis aliquid autem ipsum eveniet illo laboriosam a aut temporibus quia deleniti. Voluptates officia quia rerum modi consequuntur.
      Aliquid dolor quod, sunt vitae aspernatur dolorum doloribus iste distinctio non, commodi ducimus consectetur ea blanditiis laudantium facere suscipit minima velit quibusdam. Quae omnis facilis quasi. Nesciunt ab reprehenderit natus.
      Accusamus, ab necessitatibus neque nostrum voluptas eius, quasi officia corporis cumque quas rem ipsam alias, id nesciunt labore inventore blanditiis delectus odit cupiditate architecto? Vitae exercitationem dignissimos quod ab similique!
      Id soluta ducimus nobis eos dolor! Voluptate obcaecati accusantium quo dolor sed eum maiores quibusdam. Earum a aperiam, cumque expedita deleniti neque voluptatibus esse omnis ex iusto, nobis laborum pariatur?
      Natus, quod? Voluptas voluptatibus tempore nostrum quos, magni voluptatum dolore numquam, aliquam itaque eos distinctio? Architecto, commodi quisquam sequi maxime obcaecati tempore inventore laudantium beatae facere amet reiciendis incidunt iusto?
      Nam enim nesciunt quo doloremque neque, eos dolorem dolores inventore earum laudantium illo dignissimos quae praesentium? Perferendis, pariatur vel! Ea possimus minus rerum fugit reiciendis quam nulla eaque rem aperiam?
      Enim inventore, soluta cum qui repellat ducimus dolor ratione expedita architecto sunt obcaecati ullam fugiat impedit. Facere ex quibusdam, suscipit sit ea harum libero quia, eaque eos, asperiores odit fugit.
      Officia rerum, voluptatem ea minima autem consectetur harum veniam tempore minus commodi dignissimos ipsum repellendus porro ullam architecto laboriosam reprehenderit dicta, provident qui consequuntur. Facere modi aut rerum nam? Rem!
      Fugiat est consectetur quas ex, quo necessitatibus nostrum obcaecati voluptates adipisci totam ut dignissimos perspiciatis reprehenderit dolorem rerum iste labore optio ipsum non eos! Nulla corrupti ipsum nihil debitis quasi.
      Tempore eius harum saepe deleniti, earum soluta dolorum officiis vero numquam ut, culpa illo voluptas fugiat pariatur asperiores? Placeat doloribus enim eligendi id ullam odio, facilis quod nisi praesentium qui.
      Quo distinctio veniam, consequatur quasi praesentium totam, nam qui atque harum, similique itaque! Cumque quisquam dolore exercitationem, quam minus rerum explicabo minima, alias vel praesentium eaque expedita molestiae id ad?
      Consectetur facilis tempora deserunt eius nesciunt! Tenetur vero blanditiis reiciendis tempore saepe ducimus qui nulla fugiat dolores, delectus molestiae cum dolore? Magni, doloribus. Vel nemo in, amet cum ipsam vero.
      Mollitia dolores quod adipisci esse officiis tenetur molestias quos ex at sit omnis natus, asperiores eius maxime, laudantium cum. Voluptatum, veritatis necessitatibus? Quod ipsa facilis eos quaerat, doloribus voluptas consequuntur?</p>
    </div>
  );
}
